resources:
  - name: customer
    label: Customer
    fields:
      - name: id
        label: ID
        type: number
        editable: false
      - name: name
        label: Name
        type: string
      - name: email
        label: Email
        type: email

  - name: part
    label: Part
    fields:
      - name: id
        label: ID
        type: number
        editable: false
      - name: name
        label: Name
        type: string
      - name: description
        label: Description
        type: text

  - name: order
    label: Order
    fields:
      - name: id
        label: ID
        type: number
        editable: false
      - name: customer_id
        label: Customer ID
        type: reference
        reference: customer
      - name: order_date
        label: Order Date
        type: date
      - name: status
        label: Status
        type: string
    tabs:
      - name: details
        label: Details
        fields:
          - customer_id
          - order_date
          - status
      - name: order_items
        label: Order Items
        inline_form: true
        fields:
          - product
          - quantity
          - price

  - name: order_item
    label: Order Item
    fields:
      - name: id
        label: ID
        type: number
        editable: false
      - name: order_id
        label: Order ID
        type: reference
        reference: order
      - name: product
        label: Product
        type: string
      - name: quantity
        label: Quantity
        type: number
      - name: price
        label: Price
        type: number
